//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Api.Core.cod_service {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GET_MONEY_STATE_BY_ITEMOperationCompleted;
        
        private System.Threading.SendOrPostCallback GET_MONEY_STATE_BY_ITEM_2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::Api.Core.Properties.Settings.Default.Api_Core_cod_service_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GET_MONEY_STATE_BY_ITEMCompletedEventHandler GET_MONEY_STATE_BY_ITEMCompleted;
        
        /// <remarks/>
        public event GET_MONEY_STATE_BY_ITEM_2CompletedEventHandler GET_MONEY_STATE_BY_ITEM_2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GET_MONEY_STATE_BY_ITEM", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GET_MONEY_STATE_BY_ITEM(string ItemCode) {
            object[] results = this.Invoke("GET_MONEY_STATE_BY_ITEM", new object[] {
                        ItemCode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GET_MONEY_STATE_BY_ITEMAsync(string ItemCode) {
            this.GET_MONEY_STATE_BY_ITEMAsync(ItemCode, null);
        }
        
        /// <remarks/>
        public void GET_MONEY_STATE_BY_ITEMAsync(string ItemCode, object userState) {
            if ((this.GET_MONEY_STATE_BY_ITEMOperationCompleted == null)) {
                this.GET_MONEY_STATE_BY_ITEMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGET_MONEY_STATE_BY_ITEMOperationCompleted);
            }
            this.InvokeAsync("GET_MONEY_STATE_BY_ITEM", new object[] {
                        ItemCode}, this.GET_MONEY_STATE_BY_ITEMOperationCompleted, userState);
        }
        
        private void OnGET_MONEY_STATE_BY_ITEMOperationCompleted(object arg) {
            if ((this.GET_MONEY_STATE_BY_ITEMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GET_MONEY_STATE_BY_ITEMCompleted(this, new GET_MONEY_STATE_BY_ITEMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GET_MONEY_STATE_BY_ITEM_2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GET_MONEY_STATE_BY_ITEM_2(string ItemCode) {
            object[] results = this.Invoke("GET_MONEY_STATE_BY_ITEM_2", new object[] {
                        ItemCode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GET_MONEY_STATE_BY_ITEM_2Async(string ItemCode) {
            this.GET_MONEY_STATE_BY_ITEM_2Async(ItemCode, null);
        }
        
        /// <remarks/>
        public void GET_MONEY_STATE_BY_ITEM_2Async(string ItemCode, object userState) {
            if ((this.GET_MONEY_STATE_BY_ITEM_2OperationCompleted == null)) {
                this.GET_MONEY_STATE_BY_ITEM_2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGET_MONEY_STATE_BY_ITEM_2OperationCompleted);
            }
            this.InvokeAsync("GET_MONEY_STATE_BY_ITEM_2", new object[] {
                        ItemCode}, this.GET_MONEY_STATE_BY_ITEM_2OperationCompleted, userState);
        }
        
        private void OnGET_MONEY_STATE_BY_ITEM_2OperationCompleted(object arg) {
            if ((this.GET_MONEY_STATE_BY_ITEM_2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GET_MONEY_STATE_BY_ITEM_2Completed(this, new GET_MONEY_STATE_BY_ITEM_2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GET_MONEY_STATE_BY_ITEMCompletedEventHandler(object sender, GET_MONEY_STATE_BY_ITEMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GET_MONEY_STATE_BY_ITEMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GET_MONEY_STATE_BY_ITEMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GET_MONEY_STATE_BY_ITEM_2CompletedEventHandler(object sender, GET_MONEY_STATE_BY_ITEM_2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GET_MONEY_STATE_BY_ITEM_2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GET_MONEY_STATE_BY_ITEM_2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591